name: Topo Telemetry
on:
  issues:
    types: [labeled, unlabeled]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Signal to Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: "The Topo"
          details: "Roadmap Update: [${{ github.event.issue.title }}] status changed to: ${{ github.event.label.name }}"
          webhookUrl: ${{ secrets.DISCORD_PROJECT_WEBHOOK }}